---
version: '3'
services:

  # NZBget container
  nzbget:
    image: 'linuxserver/nzbget:latest'
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Los_Angeles
    volumes:
      - '/data/downloads:/downloads'
      - '/data/services/nzbget:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '6789:6789'

  # Sonarr container
  sonarr:
    image: 'linuxserver/sonarr:latest'
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - nzbget
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/London
    volumes:
      - '/data/downloads/completed:/data/completed'
      - '/data/media/tv:/tv'
      - '/data/services/sonarr:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '8989:8989'

  # Radarr conatainer
  radarr:
    image: 'linuxserver/radarr:latest'
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - nzbget
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/London
    volumes:
      - '/data/downloads/completed:/data/completed'
      - '/data/media/movies:/movies'
      - '/data/services/radarr:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '7878:7878'

  # Jackett conatainer
  jackett:
    image: 'linuxserver/jackett:latest'
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - '/data/services/jackett:/config'
      - '/data/downloads:/downloads'
    ports:
      - '9117:9117'
    restart: unless-stopped

  # Jellyfin container
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    user: 1001:1001
    environment:
      - TZ=Europe/London
    volumes:
      - /data/services/jellyfin:/config
      - /data/media/tv:/data/tvshows
      - /data/media/movies:/data/movies
      - /etc/letsencrypt/keys:/etc/keys
      - /data/cache:/cache
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  # Transmission with vpn container
  transmission-openvpn:
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - '/data/downloads:/data'
      - '/data/services/transmission:/config'
    environment:
      - OPENVPN_PROVIDER=PRIVADO
      - OPENVPN_CONFIG=fra-001,fra-002,fra-003,fra-004,fra-005,fra-006,fra-007,fra-008,beg-001,mad-001,osl-001,sin-001,zrh-001
      - OPENVPN_USERNAME=nhyeowvjxvwg
      - OPENVPN_PASSWORD=9pG%ZKT&
        #      - LOCAL_NETWORK=51.83.77.253/32
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
      - '51413:51413'
    image: haugene/transmission-openvpn

  # Transmission with vpn container
  transmission:
    links:
      - transmission-openvpn:transmission
    ports:
      - '8080:8080'
    image: haugene/transmission-openvpn-proxy
