---
version: '3'
services:

  # NZBget container
  nzbget:
    image: 'linuxserver/nzbget:latest'
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Los_Angeles
    volumes:
      - '/data/downloads:/data/downloads'
      - '/data/services/nzbget:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '6789:6789'

  # Sonarr container
  sonarr:
    image: 'linuxserver/sonarr:latest'
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - nzbget
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/London
    volumes:
      - '/data/downloads:/data/downloads'
      - '/data/media/tv:/data/media/tv'
      - '/data/services/sonarr:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '8989:8989'
      
  # Radarr conatainer
  radarr:
    image: 'linuxserver/radarr:latest'
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - nzbget
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/London
    volumes:
      - '/data/downloads:/data/downloads'
      - '/data/media/movies:/data/media/movies'
      - '/data/services/radarr:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '7878:7878'

  # Jackett conatainer
  jackett:
    image: 'linuxserver/jackett:latest'
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - '/data/services/jackett:/config'
      - '/data/downloads:/downloads'
    ports:
      - '9117:9117'
    restart: unless-stopped

  # Transmission container
  transmission:
    image: 'linuxserver/transmission:latest'
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=SNK
      - PASS=SNK
    volumes:
      - '/data/services/transmission:/config'
      - '/data/downloads:/downloads'
      - '/data/watch:/watch'
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'
    restart: unless-stopped
